export const musicQuotes = [
  {
    quote: "It's better to burn out than to fade away.",
    author: "Kurt Cobain",
    lang: "en",
    translation_zh: "与其苟延残喘，不如从容燃烧。",
    image: "/quotes/kurt.jpg",
  },
  {
    quote: "Life is what happens when you're busy making other plans.",
    author: "John Lennon",
    lang: "en",
    translation_zh: "生活就是当你忙着制定其他计划时发生的事。",
    image: "/quotes/lennon.jpg",
  },
  {
    quote: "The times they are a-changin'.",
    author: "Bob Dylan",
    lang: "en",
    translation_zh: "时代正在改变。",
    image: "/quotes/dylan.jpg",
  },
  {
    quote: "I don't know where I'm going from here, but I promise it won't be boring.",
    author: "David Bowie",
    lang: "en",
    translation_zh: "我不知道接下来要去哪里，但我保证不会无聊。",
    image: "/quotes/bowie.jpg",
  },
  {
    quote: "The show must go on.",
    author: "Freddie Mercury",
    lang: "en",
    translation_zh: "演出必须继续。",
    image: "/quotes/freddie.jpg",
  },
  {
    quote: "One good thing about music, when it hits you, you feel no pain.",
    author: "Bob Marley",
    lang: "en",
    translation_zh: "音乐的美妙之处在于，当它击中你时，你感觉不到痛。",
    image: "/quotes/marley.jpg",
  },
  {
    quote: "Music doesn't lie. If there is something to be changed in this world, then it can only happen through music.",
    author: "Jimi Hendrix",
    lang: "en",
    translation_zh: "音乐不会说谎。如果这个世界有什么需要改变，那只能通过音乐。",
    image: "/quotes/hendrix.jpg",
  },
  {
    quote: "Do not fear mistakes. There are none.",
    author: "Miles Davis",
    lang: "en",
    translation_zh: "不要害怕犯错。根本没有错误。",
    image: "/quotes/miles.jpg",
  },
  {
    quote: "There is a crack in everything. That's how the light gets in.",
    author: "Leonard Cohen",
    lang: "en",
    translation_zh: "万物皆有裂痕，那是光照进来的地方。",
    image: "/quotes/cohen.jpg",
  },
  {
    quote: "Music is the shorthand of emotion.",
    author: "Leo Tolstoy",
    lang: "en",
    translation_zh: "音乐是情感的速记。",
    image: "/quotes/tolstoy.jpg",
  },
  {
    quote: "Without music, life would be a mistake.",
    author: "Friedrich Nietzsche",
    lang: "en",
    translation_zh: "没有音乐，生命将是一个错误。",
    image: "/quotes/nietzsche.jpg",
  },
  {
    quote: "假如有一天我不在了，我的歌还在。",
    author: "崔健",
    lang: "zh",
    translation_en: "If one day I'm gone, my songs will remain.",
    image: "/quotes/cuijian.jpg",
  },
  {
    quote: "音乐是时间的切片，也是我们一遍遍活过的证据。",
    author: "拾音 / Pickup",
    lang: "zh",
    translation_en: "Music is a slice of time, and proof that we have lived again and again.",
    image: "/quotes/pickup.jpg",
  },
  {
    quote: "我不能改变这个世界，但我的音乐不会妥协。",
    author: "窦唯",
    lang: "zh",
    translation_en: "I can't change this world, but my music won't compromise.",
    image: "/quotes/douwei.jpg",
  },
  {
    quote: "Where words fail, music speaks.",
    author: "Hans Christian Andersen",
    lang: "en",
    translation_zh: "当语言无能为力时，音乐开口说话。",
    image: "/quotes/andersen.jpg",
  },
  {
    quote: "Music expresses that which cannot be said and on which it is impossible to be silent.",
    author: "Victor Hugo",
    lang: "en",
    translation_zh: "音乐表达了那些无法言说、却又不能沉默的东西。",
    image: "/quotes/hugo.jpg",
  },
  {
    quote: "I think music in itself is healing.",
    author: "Billy Joel",
    lang: "en",
    translation_zh: "我认为音乐本身就是治愈。",
    image: "/quotes/billy.jpg",
  },
  {
    quote: "Music is the strongest form of magic.",
    author: "Marilyn Manson",
    lang: "en",
    translation_zh: "音乐是最强大的魔法形式。",
    image: "/quotes/manson.jpg",
  },
  {
    quote: "音楽は自由だ。",
    author: "坂本龍一",
    lang: "ja",
    translation_zh: "音乐是自由的。",
    translation_en: "Music is freedom.",
    image: "/quotes/sakamoto.jpg",
  },
  {
    quote: "Reality leaves a lot to the imagination.",
    author: "John Lennon",
    lang: "en",
    translation_zh: "现实给想象力留下了很多空间。",
    image: "/quotes/lennon.jpg",
  },
  {
    quote: "We're just two lost souls swimming in a fish bowl.",
    author: "Pink Floyd",
    lang: "en",
    translation_zh: "我们不过是鱼缸里游泳的两个迷失灵魂。",
    image: "/quotes/pinkfloyd.jpg",
  },
  {
    quote: "Music is a world within itself, with a language we all understand.",
    author: "Stevie Wonder",
    lang: "en",
    translation_zh: "音乐是一个自成一体的世界，拥有我们都能理解的语言。",
    image: "/quotes/stevie.jpg",
  },
  {
    quote: "The only truth is music.",
    author: "Jack Kerouac",
    lang: "en",
    translation_zh: "唯一的真理是音乐。",
    image: "/quotes/kerouac.jpg",
  },
  {
    quote: "I'm not afraid of death. I just don't want to be there when it happens.",
    author: "Thom Yorke",
    lang: "en",
    translation_zh: "我不怕死亡。我只是不想在它发生时在场。",
    image: "/quotes/thom.jpg",
  },
  {
    quote: "不是我选择了摇滚，是摇滚选择了我。",
    author: "郑钧",
    lang: "zh",
    translation_en: "I didn't choose rock and roll — rock and roll chose me.",
    image: "/quotes/zhengjun.jpg",
  },
  {
    quote: "Every artist was first an amateur.",
    author: "Ralph Waldo Emerson",
    lang: "en",
    translation_zh: "每个艺术家最初都是业余爱好者。",
    image: "/quotes/emerson.jpg",
  },
  {
    quote: "Music can change the world because it can change people.",
    author: "Bono",
    lang: "en",
    translation_zh: "音乐能改变世界，因为它能改变人。",
    image: "/quotes/bono.jpg",
  },
  {
    quote: "After silence, that which comes nearest to expressing the inexpressible is music.",
    author: "Aldous Huxley",
    lang: "en",
    translation_zh: "在沉默之后，最接近表达不可表达之物的，是音乐。",
    image: "/quotes/huxley.jpg",
  },
  {
    quote: "我们的音乐不是用来听的，是用来活的。",
    author: "谢天笑",
    lang: "zh",
    translation_en: "Our music isn't meant to be heard — it's meant to be lived.",
    image: "/quotes/xietianxiao.jpg",
  },
  {
    quote: "To live is the rarest thing in the world. Most people exist, that is all.",
    author: "Morrissey",
    lang: "en",
    translation_zh: "活着是世上最稀罕的事。大多数人只是存在，仅此而已。",
    image: "/quotes/morrissey.jpg",
  },
  {
    quote: "If music be the food of love, play on.",
    author: "William Shakespeare",
    lang: "en",
    translation_zh: "如果音乐是爱情的食粮，那就继续演奏吧。",
    image: "/quotes/shakespeare.jpg",
  },
  {
    quote: "People haven't always been there for me, but music always has.",
    author: "Taylor Swift",
    lang: "en",
    translation_zh: "人们不总是在我身边，但音乐一直都在。",
    image: "/quotes/taylor.jpg",
  },
]
