-- 搜索结果缓存表
CREATE TABLE IF NOT EXISTS search_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_key TEXT UNIQUE NOT NULL,
  search_type TEXT NOT NULL CHECK (search_type IN ('album', 'artist', 'user')),
  results JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 索引优化查询性能
CREATE INDEX IF NOT EXISTS idx_search_cache_lookup ON search_cache(search_key, search_type);
CREATE INDEX IF NOT EXISTS idx_search_cache_updated ON search_cache(updated_at);

-- 自动更新 updated_at 触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_search_cache_updated_at
  BEFORE UPDATE ON search_cache
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- 自动清理7天前的缓存（可选）
CREATE OR REPLACE FUNCTION clean_old_search_cache()
RETURNS void AS $$
BEGIN
  DELETE FROM search_cache WHERE updated_at < NOW() - INTERVAL '7 days';
END;
$$ LANGUAGE plpgsql;

-- 每天凌晨3点自动清理（需要 pg_cron 扩展）
-- SELECT cron.schedule('clean-search-cache', '0 3 * * *', 'SELECT clean_old_search_cache()');
